### ISSUE TITLE
Erros on npm run build.prod

### ISSUE THREAD

**Issue by andvasp** [DeviantJS/angular2-seed-material2#40] opened 2016-07-16 11:53 UTC
I run the command below and expected this works. npm start run perfectly but the run build not.

npm run build.prod

'build.bundles.app' errored after 2.25 s
Error on fetch for @angular2-material/card.js at file:///C:/Temp/angular2-seed-material2/node_modules/@angular2-material/card.js
        Loading dist/tmp/app/+about/about.component.js
        Loading dist/tmp/app/+about/index.js
        Loading dist/tmp/app/app.routes.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open 'C:\Temp\angular2-seed-material2\node_modules\@angular2-material\card.js'
    at Error (native)
'build.prod' errored after 27 s
Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for @angular2-material/card.js at file:///C:/Temp/angular2-seed-material2/node_modules/@angular2-material/card.js
        Loading dist/tmp/app/+about/about.component.js
        Loading dist/tmp/app/+about/index.js
        Loading dist/tmp/app/app.routes.js
        Loading dist/tmp/app/main.js
        ENOENT: no such file or directory, open 'C:\Temp\angular2-seed-material2\node_modules\@angular2-material\card.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'C:\Temp\angular2-seed-material2\node_modules\@angular2-material\card.js'
Stack:
Error on fetch for @angular2-material/card.js at file:///C:/Temp/angular2-seed-material2/node_modules/@angular2-material/card.js
        Loading dist/tmp/app/+about/about.component.js
        Loading dist/tmp/app/+about/index.js
        Loading dist/tmp/app/app.routes.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open 'C:\Temp\angular2-seed-material2\node_modules\@angular2-material\card.js'
    at Error (native)

**Comment by carol-braileanu** [comment] 2016-08-06 17:01
Any update on this issue? I am having it as well.

**Comment by JohnnyQQQQ** [comment] 2016-08-18 16:35
@andvasp @carol-braileanu  - Couldn't reproduce, please test again with the latest version

**Comment by JohnnyQQQQ** [comment] 2016-08-23 08:58
I close this for now, feel free to reopen

**Closed by JohnnyQQQQ** 2016-08-23 08:58 UTC
